---
- name: Install Grafana
  hosts: demo
  become: yes
  tasks:
    - name: Import Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
      become: yes

    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
      become: yes

    - name: Update APT package cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: present
      become: yes

    - name: Start Grafana server
      systemd:
        name: grafana-server
        state: started
        enabled: yes
      become: yes

