- hosts: "ubuntu"
  become: yes
  tasks:
    - name: Update Ubuntu
      apt:
        update_cache: yes
        upgrade: 'yes'
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: yes
    - name: Start qemu-guest-agent service
      systemd:
        name: qemu-guest-agent
        state: started

    - name: Enable qemu-guest-agent service to start at boot
      systemd:
        name: qemu-guest-agent
        enabled: yes
